kernel myenv

<div style="font-family: Arial, sans-serif; font-size: 24px; font-weight: bold;">
    PRIMERA SECCIÓN. INTRODUCCIÓN
</div>

FUNCIONES MATEMÁTICAS
uso de math.nombre()
https://docs.python.org/3/library/math.html

In [4]:
import math as mt
from math import *   #para no tener que usar mt cada que ocupe una funcion
sqrt(4) #no necesito usar print(), solo pongo la variable o la funcion

2.0

NÚMEROS COMPLEJOS
unidad de los imaginarios es 1j,en lugar de i.
Puedes definir un complejo con la notación a + b*1j o con la notación complex(a,b)
-Operaciones:
suma
resta
division
multiplicacion

In [5]:
com1=complex(8,5)
com2=complex(2,6)
comp4=com1+4
print("la suma de un real y un complejo",comp4)
#comandos
r=com1.real
c=com1.imag
cc=com1.conjugate()
c

la suma de un real y un complejo (12+5j)


5.0

FUNCIONES DE VARIABLES COMPLEJAS
en lugar de usar math, se usa cmath para números complejos

In [6]:
from cmath import sin, sinh, exp, cos
r1=sin(8j)
r2=sinh(6j)*e  #puedo seguir usando opciones de math
r3=4j*exp(7j)
r3 #imprime (-2.6279463948751562+3.0156090173732184j), donde -2.6279463948751562 es la parte real y +3.0156090173732184j la imaginaria

(-2.6279463948751562+3.0156090173732184j)

NÚMERO REAL A IMAGINARIO
numero imaginario: 3i
numero complejo(parte real e imaginaria): 2+3i
si tengo un numero real x1=2 y la convierto en imaginaria con 1j

In [7]:
x1=2
x2=2*1j
x2

2j

FUNCIONES EN EL PLANO COMPLEJO
uso de:
from numpy.lib.scimath import *
para funciones con números complejos y reales al mismo tiempo (plano complejo)

In [8]:
from numpy.lib.scimath import *

DERIVADAS E INTEGRALES SIMBÓLICAS

symbols # expresiones simbólicas (representar expresiones algebraicas y matemáticas sin asignarles valores numéricos) 
diff    # derivada de una expresión simbólica con respecto a una variable: diff(expresion, x) seg derivada diff(expresion,x,x)
integrate # integral de una expresión simbólica con respecto de una variable: integrate(expresion, x)
Rational # definir números racionales, es decir, fracciones con numerador y denominador enteros: Rational(1, 3)  # Representa 1/3
lambdify # convertir expresiones simbólicas en funciones que pueden ser evaluadas: f = lambdify(x, expresion), result = f(2)  # Evalúa la expresión en x = 2
solve # encontrará los valores de x (raices con x=0) que satisfacen esta ecuación :solve(equation, x) 

Podemos ver como funciona la diferenciacion e integracion simbolica usando la expresipon v_0t-(1/2)gt^2
Ej. Derivar y luego integrar para regresar a la expresión original de caída libre con respecto al tiempo

In [16]:
from sympy import symbols, diff,integrate, Rational, lambdify,solve
v0,g,t=symbols('v0,g,t')  #en primer lugar todas nuestras variables son símbolos
y=v0*t-Rational(1,2)*g*t**2  #expresión simbólica
print("y=",y)
#derivar
der1=diff(y,t)
print("y'=",der1)
#integrar
int1=integrate(der1,t)
print("la integral de y' es:",int1)
f=lambdify((t,v0,g),y)
print(f(5,10,9.8))
roots = solve(y, t) #resuelve cuando y=0 para t
#print ('Las raices son', roots) 
#print ('La primera raiz es', roots[0])
#print ('La primera raiz es', roots[1])

y= -g*t**2/2 + t*v0
y'= -g*t + v0
la integral de y' es: -g*t**2/2 + t*v0
-72.5


SERIE DE TAYLOR


<div style="font-family: Arial, sans-serif; font-size: 24px; font-weight: bold;">
    SEGUNDA SECCIÓN. ÁLGEBRA LINEAL
</div>

<div style="font-family: Arial, sans-serif; font-size: 24px; font-weight: bold;">
    TERCERA SECCIÓN. REPASO DE FÍSICA
</div>

ECUACIONES DE CINEMATICA (LINEAL)
v=dx/dt ---1
integrando la expresion 1

me dará vt=x2-x1   
con limites de integracion en ambas integrales

la segunda derivada de la expresion 1 sera la aceleracion que integraremos 
a=dv/dt

me dará 1/2at^2=x2-x1 (2)
la integral de aceleracion con limites de de integracion de 0 a t


entonces
v=deltax/deltat
v=x2-x1/t2-t1
v=x2-x1/t  ---3 cuando t1=0

vt=x2-x1
x2=x1+v1f   (1)

tenemos aceleracion como
a=v2-v1/f

sustituimos esta aceleracion en la expresion (2)
1/2(v2-v1/f)t^2=x2-x1

queda (vf-v1)t=2(x2-x1)  (3)

vf^2-v1^2=2a(x2-x1)      (4)

ECUACIONES DE 
tenemos un circulo de radio r y angulo theta 
perimetro
2pir

el arco de la circunferencia(un cachito de la circunferencia(s))
s=r(theta)

velocidad lineal
v=dx/df

aceleracion lineal
a=dv/dt

velocidad angular
w=d(theta)/dt

aceleracion angular
alfa=dw/dt= d^2(theta)/dt^2

relación velocidad angular y lineal
wr=v

relacion ac angular y lineal
alfa(r)=a

si tenemos
w=d(theta)/dt
y
alfa=dw/dt
queremos escribir nuestras ecuaciones de cinematica en su forma angular, la enterior era lineal
ECUACIONES DE CINEMATICA (ANGULAR)
wf=theta1+w1t           (1.1)
theta2=theta1+v1t+(1/2)alfa(t^2)    (2.1)
w2^2-w1^2=2alfa(theta1-theta2)         (3.1)
theta2=theta1+(1/2)(w2-w1)t          (4.1)

trabajaremos con (2.1)
si tenemos las ecuaciones lineales siguientes

theta1+v1t+(1/2)alfa(t^2)=theta2
9-2t+5t^2=2
8+4t-5t^2=5  
2-9t-3t^2=0
estas ecuaciones representan un movimiento angular de algun cosa, tenemos diferentes valores en thetas y alfa y v, menos en t, que es lo que buscaremos

de forma matricial
([9,-2,5],[8,4,-5],[2,-9,-3])([t1],[t2],[t3])=([2],[5],[0])
queremos conocer el tiempo en el que sucede esto, resolvemos para la matriz ([t1],[t2],[t3])
es :\n',gaussElimin(a,b))

In [4]:
import numpy as np
a = np.array([[9.0,-2.0,5.0], [8.0,4.0,-5.0], [2.0,-9.0,-3.0]])
print('La matriz de coeficientes es:\n ', a)
b = np.array([[2.0], [5.0], [0.0]])
n = len(b)
print('La matriz constante es:\n ', b)

matriz_aumentada = np.concatenate((a,b), axis=1, dtype=float)
print('La matriz aumentada es :\n', matriz_aumentada)


def gaussElimin(a,b):
  # Fase de eliminacion
  for k in range(0,n-1):
    for i in range(k+1,n):
      if matriz_aumentada[i,k] != 0.0:
        lam = matriz_aumentada[i,k]/matriz_aumentada[k,k]
        matriz_aumentada[i] = matriz_aumentada[i] - lam*matriz_aumentada[k]
        b[i] = b[i] - lam*b[k]
       
  # Fase de sustitucion hacia atras
  for k in range(n-1,-1,-1):
    b[k] = (b[k] - np.dot(matriz_aumentada[k,k+1:n],b[k+1:n]))/matriz_aumentada[k,k]
  return b


print('El vector solución es :\n',gaussElimin(a,b))

La matriz de coeficientes es:
  [[ 9. -2.  5.]
 [ 8.  4. -5.]
 [ 2. -9. -3.]]
La matriz constante es:
  [[2.]
 [5.]
 [0.]]
La matriz aumentada es :
 [[ 9. -2.  5.  2.]
 [ 8.  4. -5.  5.]
 [ 2. -9. -3.  0.]]
El vector solución es :
 [[ 0.39213603]
 [ 0.16684378]
 [-0.23910733]]


Un coche se mueve en linea recta y parte del reposo.se sabe que el coche

usaremos la ecuacion
x2=x1+v1t+(1/2)at^2

datos 1
x1=0
t=5
x2=50
v1=0

nuestra ecuacion 1 en primeros 5 segundos seria
50=(1/2)a(5)^2

datos 2
x1=50
t=3
a=0


nuestra ecuacion 2 en los siguientes 3 segundos seria
v2=at

v2=a(5)

datos 3
v2=a(5)

nuestra ecuacion 3  seria
xf=v2(2)-(1/2)(-vf/2)(2)^2

xf=3v2

nuestro sistema de ecuaciones lineales es entonces
25a=100
vf-5a=0
x2-3v2=0

([0,0,25],[0,1,-5],[1,-3,0])(x2,v2,a)=(0,0,100)

In [8]:
a = np.array([[0.0,0.0,25.0], [0.0,1.0,-5.0], [1.0,-3.0,0.0]])
print('La matriz de coeficientes es:\n ', a)
b = np.array([[0.0], [0.0], [100.0]])
n = len(b)
print('La matriz constante es:\n ', b)

matriz_aumentada = np.concatenate((a,b), axis=1, dtype=float)
print('La matriz aumentada es :\n', matriz_aumentada)


def gaussElimin(a,b):
  # Fase de eliminacion
  for k in range(0,n-1):
    for i in range(k+1,n):
      if matriz_aumentada[i,k] != 0.0:
        lam = matriz_aumentada[i,k]/matriz_aumentada[k,k]
        matriz_aumentada[i] = matriz_aumentada[i] - lam*matriz_aumentada[k]
        b[i] = b[i] - lam*b[k]
       
  # Fase de sustitucion hacia atras
  for k in range(n-1,-1,-1):
    b[k] = (b[k] - np.dot(matriz_aumentada[k,k+1:n],b[k+1:n]))/matriz_aumentada[k,k]
  return b


print('El vector solución es :\n',gaussElimin(a,b))

La matriz de coeficientes es:
  [[ 0.  0. 25.]
 [ 0.  1. -5.]
 [ 1. -3.  0.]]
La matriz constante es:
  [[  0.]
 [  0.]
 [100.]]
La matriz aumentada es :
 [[  0.   0.  25.   0.]
 [  0.   1.  -5.   0.]
 [  1.  -3.   0. 100.]]
El vector solución es :
 [[nan]
 [nan]
 [nan]]


C:\Users\CC_15\AppData\Local\Temp\ipykernel_12784\1771473699.py:16: RuntimeWarning: divide by zero encountered in scalar divide
  lam = matriz_aumentada[i,k]/matriz_aumentada[k,k]
C:\Users\CC_15\AppData\Local\Temp\ipykernel_12784\1771473699.py:17: RuntimeWarning: invalid value encountered in multiply
  matriz_aumentada[i] = matriz_aumentada[i] - lam*matriz_aumentada[k]
C:\Users\CC_15\AppData\Local\Temp\ipykernel_12784\1771473699.py:18: RuntimeWarning: invalid value encountered in multiply
  b[i] = b[i] - lam*b[k]
