kernel myenv

<div style="font-family: Arial, sans-serif; font-size: 24px; font-weight: bold;">
    PRIMERA SECCIÓN. INTRODUCCIÓN
</div>

FUNCIONES MATEMÁTICAS
uso de math.nombre()
https://docs.python.org/3/library/math.html

In [4]:
import math as mt
from math import *   #para no tener que usar mt cada que ocupe una funcion
sqrt(4) #no necesito usar print(), solo pongo la variable o la funcion

2.0

NÚMEROS COMPLEJOS
unidad de los imaginarios es 1j,en lugar de i.
Puedes definir un complejo con la notación a + b*1j o con la notación complex(a,b)
-Operaciones:
suma
resta
division
multiplicacion

In [5]:
com1=complex(8,5)
com2=complex(2,6)
comp4=com1+4
print("la suma de un real y un complejo",comp4)
#comandos
r=com1.real
c=com1.imag
cc=com1.conjugate()
c

la suma de un real y un complejo (12+5j)


5.0

FUNCIONES DE VARIABLES COMPLEJAS
en lugar de usar math, se usa cmath para números complejos

In [6]:
from cmath import sin, sinh, exp, cos
r1=sin(8j)
r2=sinh(6j)*e  #puedo seguir usando opciones de math
r3=4j*exp(7j)
r3 #imprime (-2.6279463948751562+3.0156090173732184j), donde -2.6279463948751562 es la parte real y +3.0156090173732184j la imaginaria

(-2.6279463948751562+3.0156090173732184j)

NÚMERO REAL A IMAGINARIO
numero imaginario: 3i
numero complejo(parte real e imaginaria): 2+3i
si tengo un numero real x1=2 y la convierto en imaginaria con 1j

In [7]:
x1=2
x2=2*1j
x2

2j

FUNCIONES EN EL PLANO COMPLEJO
uso de:
from numpy.lib.scimath import *
para funciones con números complejos y reales al mismo tiempo (plano complejo)

In [8]:
from numpy.lib.scimath import *

DERIVADAS E INTEGRALES SIMBÓLICAS

symbols # expresiones simbólicas (representar expresiones algebraicas y matemáticas sin asignarles valores numéricos) 
diff    # derivada de una expresión simbólica con respecto a una variable: diff(expresion, x) seg derivada diff(expresion,x,x)
integrate # integral de una expresión simbólica con respecto de una variable: integrate(expresion, x)
Rational # definir números racionales, es decir, fracciones con numerador y denominador enteros: Rational(1, 3)  # Representa 1/3
lambdify # convertir expresiones simbólicas en funciones que pueden ser evaluadas: f = lambdify(x, expresion), result = f(2)  # Evalúa la expresión en x = 2
solve # encontrará los valores de x (raices con x=0) que satisfacen esta ecuación :solve(equation, x) 

Podemos ver como funciona la diferenciacion e integracion simbolica usando la expresipon v_0t-(1/2)gt^2
Ej. Derivar y luego integrar para regresar a la expresión original de caída libre con respecto al tiempo

In [16]:
from sympy import symbols, diff,integrate, Rational, lambdify,solve
v0,g,t=symbols('v0,g,t')  #en primer lugar todas nuestras variables son símbolos
y=v0*t-Rational(1,2)*g*t**2  #expresión simbólica
print("y=",y)
#derivar
der1=diff(y,t)
print("y'=",der1)
#integrar
int1=integrate(der1,t)
print("la integral de y' es:",int1)
f=lambdify((t,v0,g),y)
print(f(5,10,9.8))
roots = solve(y, t) #resuelve cuando y=0 para t
#print ('Las raices son', roots) 
#print ('La primera raiz es', roots[0])
#print ('La primera raiz es', roots[1])

y= -g*t**2/2 + t*v0
y'= -g*t + v0
la integral de y' es: -g*t**2/2 + t*v0
-72.5


SERIE DE TAYLOR(aproximaciones)

La representación de la expresión expr en Serie de Taylor de orden **n**, en la variable **t** alrededor de **t0**, se calcula como                       
**expr.series(t, t0, n)**.
                        


In [9]:
from sympy import symbols, exp, sin, cos, simplify, expand

#para la funcion e^t 
t = symbols('t')
exp(t).series(t, 0, 3)

#para la funcion e^sen(t)
t = symbols('t')
f = exp(sin(t))
f.series(t, 0, 8)


1 + t + t**2/2 - t**4/8 - t**5/15 - t**6/240 + t**7/90 + O(t**8)


Puedo manipular las epxresiones puedo usar **expand** y **simplify**.   

In [26]:
#funcion -sin(x)*sin(y) + cos(x)*cos(y)
x, y = symbols('x y')
f = -sin(x)*sin(y) + cos(x)*cos(y)

print("normal:",f)
print("simplificada:",simplify(f))
print("expandida:", expand(f))

print("serie de taylor de orden 5, al rededor de 0 en la variable t :",f.series(x,0,5)) #ejemplo de serie de taylor

#ejemplo para otra funcion
x1, y1 = symbols('x1 y1')
expand(sin(x1+y1), trig=True) # con un hint, expande la funcion con propiedades trigonometricas, en este caso usa la propiedad sin(x+y)=sin(x)cos(y),etc




normal: -sin(x)*sin(y) + cos(x)*cos(y)
simplificada: cos(x + y)
expandida: -sin(x)*sin(y) + cos(x)*cos(y)
serie de taylor de orden 5, al rededor de 0 en la variable t : cos(y) - x*sin(y) - x**2*cos(y)/2 + x**3*sin(y)/6 + x**4*cos(y)/24 + O(x**5)


sin(x1)*cos(y1) + sin(y1)*cos(x1)

<div style="font-family: Arial, sans-serif; font-size: 24px; font-weight: bold;">
    SEGUNDA SECCIÓN. ÁLGEBRA LINEAL
</div>

SISTEMA DE ECUACIONES LINEALES. 

Resolvemos x con
$$
\begin{aligned}
    &Ax = b \\
\end{aligned}
$$
tiene solucuón unica si
$$
\begin{aligned}
    &detA ≠ 0 \\
\end{aligned}
$$
Hay varios métodos para solucionar sistema de ecuaciones, la que se usará es la Gauss 

Ej.

$$
\begin{aligned}
    & 4x_1 - 2x_2 + x_3 = 11 \\
    & -2x_1 =  \\
    &\omega_f^2 = \omega_i^2 + 2\alpha (\theta_f - \theta_i) 
\end{aligned}
$$


CONDICIONES DE SINGULARIDAD DE LA MATRIZ(determinar la singularidas)

-Criterio
$$
\begin{aligned}
    &detA<<||A|| \\
\end{aligned}
$$

la norma es la raíz cuadrada de la suma de los cuadrados de todos los elementos de la matriz.
$$
\| \mathbf{A} \|_e = \sqrt{\sum_{i=1}^{n} \sum_{j=1}^{n} |A_{ij}|^2}
$$




-Número de condición de matriz
indica cuánto puede cambiar la solución si hay pequeños cambios en los coeficientes de la matriz o el vector constante


$$
\begin{aligned}
    &con(A) = ||A||||A^-1|| \\
\end{aligned}
$$



<div style="font-family: Arial, sans-serif; font-size: 24px; font-weight: bold;">
    TERCERA SECCIÓN. REPASO DE FÍSICA
</div>

<div style="font-family: Arial, sans-serif; font-size: 15px; font-weight: bold;">
    ECUACIONES DE CINEMATICA (LINEAL)
</div>

Movimiento con aceleración constante

$$
\begin{aligned}
    &v_f = v_i + at \\  
    &x_f = x_i + v_i t + \frac{1}{2} a t^2 \\  
    &v_f^2 = v_i^2 + 2a(x_f - x_i) \\   
    &x_f - x_i = \frac{(v_i + v_f)}{2} t    
\end{aligned}
$$

<div style="font-family: Arial, sans-serif; font-size: 15px; font-weight: bold;">
    ECUACIONES DE CINEMÁTICA (ANGULAR)
</div>

Movimiento con aceleración angular constante

$$
\begin{aligned}
    &\omega_f = \omega_i + \alpha t \\
    &\theta_f = \theta_i + \omega_i t + \frac{1}{2} \alpha t^2 \\
    &\omega_f^2 = \omega_i^2 + 2\alpha (\theta_f - \theta_i) \\
    &\theta_f - \theta_i = \frac{(\omega_i + \omega_f)}{2} t
\end{aligned}
$$

donde:
- \( \theta_i \) y \( \theta_f \) son la posición angular inicial y final, respectivamente.
- \( \omega_i \) y \( \omega_f \) son la velocidad angular inicial y final, respectivamente.
- \( \alpha \) es la aceleración angular.
- \( t \) es el tiempo.


Ejercicio1.
trabajaremos con 

$$
\begin{aligned}
    &\theta_f = \theta_i + \omega_i t + \frac{1}{2} \alpha t^2 \\
\end{aligned}
$$

si tenemos las ecuaciones lineales siguientes

$$
\begin{aligned}
    &9- 2t + 5t^2 = 2 \\
    &9 +4t - 5t^2 = 5 \\
    &2-9t - 3t^2= 0
\end{aligned}
$$

estas ecuaciones representan un movimiento angular de algun cosa, tenemos diferentes valores en thetas y alfa y v, menos en t, que es lo que buscaremos

de forma matricial

\begin{aligned}
&\begin{pmatrix} 
9 & -2 & 5 \\ 
8 & 4 & -5 \\ 
2 & -9 & -3
\end{pmatrix} 
\begin{pmatrix} 
t_1 \\ 
t_2 \\ 
t_3
\end{pmatrix} = 
\begin{pmatrix} 
2 \\ 
5 \\ 
0
\end{pmatrix}
\end{aligned}

queremos conocer el tiempo en el que sucede esto, resolvemos para la matriz ([t1],[t2],[t3])
es :\n',gaussElimin(a,b))

In [4]:
import numpy as np
a = np.array([[9.0,-2.0,5.0], [8.0,4.0,-5.0], [2.0,-9.0,-3.0]])
print('La matriz de coeficientes es:\n ', a)
b = np.array([[2.0], [5.0], [0.0]])
n = len(b)
print('La matriz constante es:\n ', b)

matriz_aumentada = np.concatenate((a,b), axis=1, dtype=float)
print('La matriz aumentada es :\n', matriz_aumentada)


def gaussElimin(a,b):
  # Fase de eliminacion
  for k in range(0,n-1):
    for i in range(k+1,n):
      if matriz_aumentada[i,k] != 0.0:
        lam = matriz_aumentada[i,k]/matriz_aumentada[k,k]
        matriz_aumentada[i] = matriz_aumentada[i] - lam*matriz_aumentada[k]
        b[i] = b[i] - lam*b[k]
       
  # Fase de sustitucion hacia atras
  for k in range(n-1,-1,-1):
    b[k] = (b[k] - np.dot(matriz_aumentada[k,k+1:n],b[k+1:n]))/matriz_aumentada[k,k]
  return b


print('El vector solución es :\n',gaussElimin(a,b))

La matriz de coeficientes es:
  [[ 9. -2.  5.]
 [ 8.  4. -5.]
 [ 2. -9. -3.]]
La matriz constante es:
  [[2.]
 [5.]
 [0.]]
La matriz aumentada es :
 [[ 9. -2.  5.  2.]
 [ 8.  4. -5.  5.]
 [ 2. -9. -3.  0.]]
El vector solución es :
 [[ 0.39213603]
 [ 0.16684378]
 [-0.23910733]]


Ejercicio 2.  Un coche se mueve en línea recta y parte del reposo. Se sabe que el coche sigue la ecuación:  

$$
\begin{aligned}
    &x_2 = x_1 + v_1 t + \frac{1}{2} a t^2
\end{aligned}
$$

Datos iniciales:
- \( x_1 = 0 \)
- \( t = 5 \)
- \( x_2 = 50 \)
- \( v_1 = 0 \)

Nuestra ecuación en los primeros 5 segundos sería:

$$
\begin{aligned}
    50 = \frac{1}{2} a (5)^2
\end{aligned}
$$

Datos en los siguientes 3 segundos:
- \( x_1 = 50 \)
- \( t = 3 \)
- \( a = 0 \)

Nuestra ecuación para la velocidad final es:

$$
\begin{aligned}
    v_2 = a(5)
\end{aligned}
$$

Última ecuación:

$$
\begin{aligned}
    x_f = v_2 (2) - \frac{1}{2} \left( -\frac{v_f}{2} \right) (2)^2
\end{aligned}
$$

Reorganizando:

$$
\begin{aligned}
    x_f = 3 v_2
\end{aligned}
$$

Sistema de ecuaciones lineales:

$$
\begin{aligned}
    &25a = 100 \\
    &v_f - 5a = 0 \\
    &x_2 - 3v_2 = 0
\end{aligned}
$$

De forma matricial:

$$
\begin{aligned}
    &\begin{pmatrix} 
    0 & 0 & 25 \\ 
    0 & 1 & -5 \\ 
    1 & -3 & 0
    \end{pmatrix} 
    \begin{pmatrix} 
    x_2 \\ 
    v_2 \\ 
    a
    \end{pmatrix} = 
    \begin{pmatrix} 
    0 \\ 
    0 \\ 
    100
    \end{pmatrix}
\end{aligned}
$$



In [8]:
a = np.array([[0.0,0.0,25.0], [0.0,1.0,-5.0], [1.0,-3.0,0.0]])
print('La matriz de coeficientes es:\n ', a)
b = np.array([[0.0], [0.0], [100.0]])
n = len(b)
print('La matriz constante es:\n ', b)

matriz_aumentada = np.concatenate((a,b), axis=1, dtype=float)
print('La matriz aumentada es :\n', matriz_aumentada)


def gaussElimin(a,b):
  # Fase de eliminacion
  for k in range(0,n-1):
    for i in range(k+1,n):
      if matriz_aumentada[i,k] != 0.0:
        lam = matriz_aumentada[i,k]/matriz_aumentada[k,k]
        matriz_aumentada[i] = matriz_aumentada[i] - lam*matriz_aumentada[k]
        b[i] = b[i] - lam*b[k]
       
  # Fase de sustitucion hacia atras
  for k in range(n-1,-1,-1):
    b[k] = (b[k] - np.dot(matriz_aumentada[k,k+1:n],b[k+1:n]))/matriz_aumentada[k,k]
  return b


print('El vector solución es :\n',gaussElimin(a,b))

La matriz de coeficientes es:
  [[ 0.  0. 25.]
 [ 0.  1. -5.]
 [ 1. -3.  0.]]
La matriz constante es:
  [[  0.]
 [  0.]
 [100.]]
La matriz aumentada es :
 [[  0.   0.  25.   0.]
 [  0.   1.  -5.   0.]
 [  1.  -3.   0. 100.]]
El vector solución es :
 [[nan]
 [nan]
 [nan]]


C:\Users\CC_15\AppData\Local\Temp\ipykernel_12784\1771473699.py:16: RuntimeWarning: divide by zero encountered in scalar divide
  lam = matriz_aumentada[i,k]/matriz_aumentada[k,k]
C:\Users\CC_15\AppData\Local\Temp\ipykernel_12784\1771473699.py:17: RuntimeWarning: invalid value encountered in multiply
  matriz_aumentada[i] = matriz_aumentada[i] - lam*matriz_aumentada[k]
C:\Users\CC_15\AppData\Local\Temp\ipykernel_12784\1771473699.py:18: RuntimeWarning: invalid value encountered in multiply
  b[i] = b[i] - lam*b[k]
