INTERSECCIÓN DE TRAYECTORIAS.
Tres objetos se mueven de tal manera que sus trayectorias son 
$$
\begin{aligned}
    &2x - y + 3z = 24 \\
    &2y - z = 14 \\
    &7x - 5y = 6
\end{aligned}
$$
encontrar su punto de interseccion

In [2]:
#matriz de coeficientes
import numpy as np
a=np.array([[2.0,-1.0,3.0],[0.0,2.0,-1.0],[7.0,-5.0,0.0]])
#matriz columna
b=np.array([[24.0],[14.0],[6.0]])

#con eliminación gaussiana
n = len(b)
matriz_aumentada = np.concatenate((a,b), axis=1, dtype=float)
print('La matriz aumentada es :\n', matriz_aumentada)
def gaussElimin(a,b):
  # Fase de eliminacion
  for k in range(0,n-1):
    for i in range(k+1,n):
      if matriz_aumentada[i,k] != 0.0:
        lam = matriz_aumentada[i,k]/matriz_aumentada[k,k]
        matriz_aumentada[i] = matriz_aumentada[i] - lam*matriz_aumentada[k]
        b[i] = b[i] - lam*b[k]
        
  # Fase de sustitucion hacia atras
  for k in range(n-1,-1,-1):
    b[k] = (b[k] - np.dot(matriz_aumentada[k,k+1:n],b[k+1:n]))/matriz_aumentada[k,k]
  return b

print('El vector solución es :\n',gaussElimin(a,b))


La matriz aumentada es :
 [[ 2. -1.  3. 24.]
 [ 0.  2. -1. 14.]
 [ 7. -5.  0.  6.]]
El vector solución es :
 [[ 8.]
 [10.]
 [ 6.]]


CARGA DE LOS QUARKS.
Los protones y neutrones están formados cada uno por tres quarks. Los protones poseen dos quarks up (u) y un quark down (d), los neutrones poseen un quark up y dos quarks down. Si la carga de un protón es igual al positivo de la carga del electrón(+e) y la carga de un neutrón es cero, determine las cargas de los quarks up y down.(suponga que +e=1)


protón=2u+d
neutrón=u+2d
1.ecuación lineal del sistema
$$
\begin{aligned}
    &2u + d = 1 \\
    &u + 2d = 0
\end{aligned}
$$
2. nuestras matrices para la formas Ax=b, donde x=(u,d) y b=(1,0)


\begin{aligned}
&\begin{pmatrix} 
2 & 1 \\ 
1 & 2 
\end{pmatrix} 
\begin{pmatrix} 
u \\ 
d 
\end{pmatrix} = 
\begin{pmatrix} 
1 \\ 
0 
\end{pmatrix}
\end{aligned}


In [4]:
a = np.array([[2.0, 1.0], [1.0, 2.0]])
print('La matriz de coeficientes es:\n ', a)

b = np.array([[1.0],[0.0]])
n = len(b)
print('La matriz constante es:\n ', b)

matriz_aumentada = np.concatenate((a,b), axis=1, dtype=float)
print('La matriz aumentada es :\n', matriz_aumentada)


def gaussElimin(a,b):
  # Fase de eliminacion
  for k in range(0,n-1):
    for i in range(k+1,n):
      if matriz_aumentada[i,k] != 0.0:
        lam = matriz_aumentada[i,k]/matriz_aumentada[k,k]
        matriz_aumentada[i] = matriz_aumentada[i] - lam*matriz_aumentada[k]
        b[i] = b[i] - lam*b[k]
     
  # Fase de sustitucion hacia atras
  for k in range(n-1,-1,-1):
    b[k] = (b[k] - np.dot(matriz_aumentada[k,k+1:n],b[k+1:n]))/matriz_aumentada[k,k]
  return b


print('las cargas de los quarks up y down son :\n',gaussElimin(a,b))

La matriz de coeficientes es:
  [[2. 1.]
 [1. 2.]]
La matriz constante es:
  [[1.]
 [0.]]
La matriz aumentada es :
 [[2. 1. 1.]
 [1. 2. 0.]]
las cargas de los quarks up y down son :
 [[ 0.66666667]
 [-0.33333333]]


METEOROS. 
El Centro de Investigación 1 examina la cantidad de meteoros que entran a la atmósfera. Con su equipo de recopilación de datos durante 8 horas captó 95kg de meteoros, por fuentes externas sabemos que fueron de 4 distintas masas (1kg, 5kg, 10kg y 20kg). La cantidad total de meteoros fue de 26. Otro centro de investigación captó que la cantidad de meteoros de 5kg es 4 veces la cantidad de meteoros de 10kg, y el número de meteoros de 1kg es 1 menos que el doble de la cantidad de meteoros de 5kg. Después use matrices para encontrar el número asociado a cada masa de meteoros.
1.nuestras ecuaciones lineales son 
$$
\begin{aligned}
    &x1 + x2 + x3 + x4 = 26 \\
    &x1 + 5x2 + 10x3 + 20x4 = 95 \\
    &      x2 - 4x3 = 0 \\
    &x1 - 2x2 = -1
\end{aligned}
$$


In [9]:
a = np.array([[1.0, 1.0, 1.0, 1.0], [1.0, 5.0, 10.0, 20.0], [0.0, 1.0, -4.0, 0.0], [1.0, -2.0, 0.0, 0.0]])
print('La matriz de coeficientes es:\n ', a)
b = np.array([[26.0], [95.0], [0.0], [-1.0]])
n = len(b)

matriz_aumentada = np.concatenate((a,b), axis=1, dtype=float)


def gaussElimin(a,b):
  # Fase de eliminacion
  for k in range(0,n-1):
    for i in range(k+1,n):
      if matriz_aumentada[i,k] != 0.0:
        lam = matriz_aumentada[i,k]/matriz_aumentada[k,k]
        matriz_aumentada[i] = matriz_aumentada[i] - lam*matriz_aumentada[k]
        b[i] = b[i] - lam*b[k]
  # Fase de sustitucion hacia atras
  for k in range(n-1,-1,-1):
    b[k] = (b[k] - np.dot(matriz_aumentada[k,k+1:n],b[k+1:n]))/matriz_aumentada[k,k]
  return b


print('El vector solución es :\n',gaussElimin(a,b))

La matriz de coeficientes es:
  [[ 1.  1.  1.  1.]
 [ 1.  5. 10. 20.]
 [ 0.  1. -4.  0.]
 [ 1. -2.  0.  0.]]
El vector solución es :
 [[15.]
 [ 8.]
 [ 2.]
 [ 1.]]
